- name: Configure devstation
  hosts: localhost
  tags: shell
  vars:
    username: johe
    default_shell: /usr/bin/zsh
    oh_my_zsh_theme: powerlevel10k/powerlevel10k
    private_github_key: ~/.ssh/github
  connection: local
  tasks:
    - name: Install packages
      become: yes
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - git
        - zsh
        - tmux
        - jq
        - nmap
        - curl

    - name: Install oh-my-zsh
      vars:
        omz_url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      ansible.builtin.shell: sh -c "$(curl -fsSL {{ omz_url }})" "" --unattended
      args:
        creates: ~/.oh-my-zsh	

    - name: Check if zsh-syntax-highlightning repo exists
      ansible.builtin.stat:
        path: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      register: zsh_syntax_res

    - name: Install zsh-syntax-highlightning
      when: not zsh_syntax_res.stat.exists
      vars:
        zsh_syntax_url: https://github.com/zsh-users/zsh-syntax-highlighting.git
      ansible.builtin.shell: git clone {{ zsh_syntax_url }} ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    - name: Check if powerlevel10k repo exists
      ansible.builtin.stat:
        path: ~/.oh-my-zsh/custom/themes/powerlevel10k
      register: powerlevel10k_res

    - name: Install powerlevel10k
      when: not powerlevel10k_res.stat.exists
      vars:
        powerlevel10k_url: https://github.com/romkatv/powerlevel10k.git
      ansible.builtin.shell: git clone --depth=1 {{ powerlevel10k_url }} ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

    - name: Create config file ~/.zshrc
      template:
        src: zshrc.j2
        dest: ~/.zshrc

    - name: Create config file ~/.vimrc
      template:
        src: vimrc.j2
        dest: ~/.vimrc

    - name: Create config file ~/.tmux
      template:
        src: tmux.j2
        dest: ~/.tmux.conf

    - name: Create folder ~/.{{ username }}/zshrc.d
      file:
        path: ~/.{{ username }}/zshrc.d
        state: directory

    - name: Create config file ~/.{{ username }}/zshrc.d/{{ username }}-conf.sh
      template:
        src: conf.j2
        dest: ~/.{{ username }}/zshrc.d/{{ username }}-conf.sh

    - name: Create folder ~/.ssh/config
      file:
        path: ~/.ssh
        state: directory

    - name: Create ssh config file
      when: private_github_key
      template:
        src: ssh.j2
        dest: ~/.ssh/config

    - name: Set default shell
      become: true
      user:
        name: "{{ username }}"
        shell: "{{ default_shell }}"
