username: "{{ lookup('env', 'USER') }}"
packages_to_install:
  - vim
  - git
  - zsh
  - tmux
  - jq
  - nmap
  - curl
default_shell: "{{ '/bin/zsh' if ansible_os_family == 'Darwin' else '/usr/bin/zsh' }}"
powerlevel10k_url: https://github.com/romkatv/powerlevel10k.git
powerlevel_10k_fonts:
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
oh_my_zsh_theme: powerlevel10k/powerlevel10k
private_github_key: ~/.ssh/github # Kan att behöva ändras
git_config:
  - key: user.name
    value: "{{ username }}"
  - key: user.email
    value: "{{ username }}@example.com"
  - key: core.editor
    value: vim
