---
- name: Install packages
  when: ansible_os_family == 'Debian'
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_packages }}"

- name: Install packages
  when: ansible_os_family == 'Darwin'
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_packages }}"
  register: result
  until: result is successful

- name: Install oh-my-zsh
  vars:
    omz_url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
  ansible.builtin.shell: sh -c "$(curl -fsSL {{ omz_url }})" "" --unattended
  args:
    creates: ~/.oh-my-zsh	

- name: Install Packer for Fedora
  when: ansible_os_family == 'RedHat'
  block:
    - name: Install dnf-plugins-core
      become: true
      ansible.builtin.package:
        name: dnf-plugins-core
        state: latest

    - name: Add HashiCorp repository to dnf config manager
      become: true
      ansible.builtin.yum_repository:
        name: hashicorp
        description: HashiCorp Stable Repository
        baseurl: https://rpm.releases.hashicorp.com/fedora/{{ ansible_distribution_major_version }}/x86_64/stable/
        gpgcheck: true
        gpgkey: https://rpm.releases.hashicorp.com/gpg
      when: ansible_distribution == 'Fedora'

    - name: Add HashiCorp repository
      become: true  
      ansible.builtin.command:
        cmd: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      when: ansible_distribution == 'AlmaLinux'

- name: Install Packer for Debian
  when: ansible_os_family == 'Debian'
  block:
    - name: Add Hashicorp GPG key
      become: true
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Hashicorp apt repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com bookworm main"
        state: present

- name: Install Packer package
  become: true
  ansible.builtin.package:
    name: packer
    state: present
...
