---
- name: Install packages
  when: ansible_os_family == 'Debian'
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_packages }}"

- name: Install packages
  when: ansible_os_family == 'Darwin'
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_packages }}"
  register: result
  until: result is successful

- name: Install oh-my-zsh
  vars:
    omz_url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
  ansible.builtin.shell: sh -c "$(curl -fsSL {{ omz_url }})" "" --unattended
  args:
    creates: ~/.oh-my-zsh	
...
