name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag devbox:$(date +%s)
  
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            flavor: debian
          - os: macos-latest
            flavor: mac 
    
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
      
      - name: Run init script
        run: ./init.bash ${{ matrix.flavor }}

      - name: Run playbook
        run: ./venv/bin/ansible-playbook ./ansible/configure.yml
